# Generated by Django 4.2.1 on 2023-08-20 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_data', models.JSONField()),
                ('property_other_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('user_id', models.SlugField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_mobile', models.CharField(max_length=200, null=True)),
                ('user_gender', models.CharField(max_length=200)),
                ('user_psw', models.CharField(max_length=200)),
                ('user_other_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='property_utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=200)),
                ('property_report', models.JSONField(default=dict)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_1.p_detail')),
            ],
        ),
        migrations.AddField(
            model_name='p_detail',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_1.user_register'),
        ),
    ]
