# Generated by Django 3.0 on 2023-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_seller_info',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('seller_id', models.CharField(max_length=11)),
                ('property_title', models.CharField(max_length=100)),
                ('selling_option', models.TextField()),
                ('property_desc', models.TextField()),
                ('property_images', models.TextField()),
                ('property_video', models.TextField()),
                ('property_current_status', models.TextField()),
                ('property_location', models.TextField()),
                ('property_other_info', models.TextField()),
                ('update_time_stamp', models.TextField()),
            ],
        ),
    ]
