# Generated by Django 4.2.6 on 2023-10-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_detail_v1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_data', models.JSONField()),
                ('property_other_data', models.JSONField(default=dict)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='property_utility_v1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=200)),
                ('property_report', models.JSONField(default=dict)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_1.p_detail_v1')),
            ],
        ),
    ]
