# Generated by Django 3.0 on 2023-01-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_seller_info',
            name='sample_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
