# Generated by Django 4.2.6 on 2023-12-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='property_utility_v1',
        ),
    ]
