# Generated by Django 3.0 on 2023-01-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0002_main_seller_info_sample_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_seller_info',
            name='sample_image',
        ),
    ]
