# Generated by Django 3.2.16 on 2023-01-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0003_remove_main_seller_info_sample_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_seller_info',
            old_name='property_images',
            new_name='property_media',
        ),
        migrations.RemoveField(
            model_name='main_seller_info',
            name='property_video',
        ),
    ]
