# Generated by Django 4.2.6 on 2023-10-21 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_1', '0003_user_other_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_other_data',
            new_name='User_other_utils',
        ),
    ]
