# Generated by Django 4.2.6 on 2023-10-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0004_rename_user_other_data_user_other_utils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_other_utils',
            old_name='user_other_data',
            new_name='user_other_data_json',
        ),
    ]
