# Generated by Django 4.2 on 2024-03-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_other_utils',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_other_utils',
            name='is_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
