# Generated by Django 3.2.16 on 2023-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0004_auto_20230122_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_seller_info',
            name='property_media',
            field=models.FileField(upload_to=''),
        ),
    ]
