# Generated by Django 5.1.4 on 2024-12-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_1", "0005_user_other_utils_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp_secret",
            field=models.CharField(max_length=250),
        ),
    ]
