# Generated by Django 3.2.16 on 2023-01-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0005_alter_main_seller_info_property_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main_seller_info',
        ),
    ]
