# Generated by Django 3.2.16 on 2023-01-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0007_property_detail_property_other_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=25)),
                ('user_mobile', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=5)),
                ('user_psw', models.CharField(max_length=10)),
            ],
        ),
    ]
