# Generated by Django 3.2.16 on 2023-01-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0008_user_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='user_mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
