# Generated by Django 3.2.16 on 2023-01-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0009_alter_user_register_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='id',
        ),
        migrations.AddField(
            model_name='user_register',
            name='user_id',
            field=models.CharField(default=None, max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property_detail',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_1.user_register'),
        ),
    ]
