# Generated by Django 3.2.16 on 2023-01-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0011_auto_20230128_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_other_detail',
            name='property_image_1',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
