# Generated by Django 3.2.16 on 2023-01-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0012_alter_property_other_detail_property_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_other_detail',
            name='property_image_1',
            field=models.FileField(upload_to='media/'),
        ),
    ]
