# Generated by Django 3.2.16 on 2023-02-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0013_alter_property_other_detail_property_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='p_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_data', models.JSONField()),
                ('seller_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_1.user_register')),
            ],
        ),
    ]
