# Generated by Django 4.1.6 on 2023-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_1", "0015_alter_property_other_detail_media_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="p_detail",
            name="id",
        ),
        migrations.AddField(
            model_name="p_detail",
            name="property_id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
