# Generated by Django 4.1.6 on 2023-02-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_1", "0017_remove_p_detail_property_id_p_detail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="user_id",
            field=models.CharField(
                max_length=11, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
